<?php
// $Id$
/**
* @file
* Module to hold my customizations to Ubercart
*/

/**
* Implementation of hook_form_alter()
*/
function ubercart_changes_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'product_node_form') {
		//print_r($form['base']);
		$form['base']['model']['#required'] = FALSE;
		$form['base']['prices']['sell_price']['#required'] = FALSE;
		$form['base']['weight'] = array();
		$form['base']['dimensions'] = array();
		$form['base']['prices']['list_price'] = array();
		$form['base']['prices']['cost'] = array();
		$form['base']['shippable'] = array();
		$form['base']['pkg_qty'] = array();
		$form['base']['default_qty'] = array();
		$form['base']['ordering'] = array();
		$form['base']['model'] = array();
	}
}
/*
function ubercart_changes_theme() {
  return array(
    'block' => array(
      'template' => 'block',
      'parameters' => array('variables' => NULL),
    ),
  );
}*/