<?php
// $Id: help.module,v 1.78.2.1 2008/04/09 21:11:48 goba Exp $
  
/**
* Implementation of hook_block().
*/
function rotator_block($op = 'list', $delta = 0) {
	global $user;
	
	if ($op == 'list') {
		$blocks[0]['info'] = t('Rotator');
		// Not worth caching.
		$blocks[0]['cache'] = BLOCK_NO_CACHE;
		return $blocks;
	}
	else if ($op == 'view') {
		drupal_add_js(drupal_get_path('module', 'rotator') .'/jqFancyTransitions.js');

		$result = db_query_range('SELECT filepath FROM {files} WHERE status=1 AND fid IN (SELECT field_image_fid FROM {content_type_rotator})', 0, 10);
		$block['content'] .= '<div id="photo" class="pics">';
		while ($node = db_fetch_object($result)) {
			$block['content'] .= theme('imagecache', 'rotator', $node->filepath);
		}
		$block['content'] .= '</div>';

		$block['subject'] = '';//t('Rotator');
		return $block;
	}
}
